#include "module_Deploy_Mast.h"
#include "module_MAST_DEP_Initialise.h"
#include "module_MAST_PAN_Initialise.h"
#include "module_MAST_TILT_Initialise.h"
#include "module_MAST_DEP_SwitchOff.h"
#include "module_MAST_PAN_SwitchOff.h"
#include "module_MAST_TILT_SwitchOff.h"
#include "module_MAST_DEP_MoveTo.h"
#include "module_MAST_PAN_MoveTo.h"
#include "module_MAST_TILT_MoveTo.h"
#include "module_MAST_PTU_MoveTo.h"

#include "module_ADE_Operational2Standby.h"
#include "module_ADEs_Activate.h"
#include "module_ADEs_DeActivate.h"
#include "module_ADE_Standby2Operational.h"
#include "module_ADE_SwitchOn.h"
#include "module_ADE_SwitchOff.h"
#include "module_ADE_ReleaseHDRM.h"
#include "module_HDRM_Release.h"

#include "module_COMMS_LST2WH.h"
#include "module_COMMS_SwitchOff.h"
#include "module_COMMS_SwitchOn.h"
#include "module_COMMS_WH2LST.h"
#include "module_Deploy_LEFT_SA.h"
#include "module_Deploy_Mast.h"
#include "module_Deploy_RIGHT_SA.h"
#include "module_DHS_HighPwr2Reduced.h"
#include "module_DHS_LowPwr2Reduced.h"
#include "module_DHS_Nominal2Reduced.h"
#include "module_DHS_Reduced2HighPwr.h"
#include "module_DHS_Reduced2LowPwr.h"
#include "module_DHS_Reduced2Nominal.h"

#include "module_GNC_Initialise.h"
#include "module_GNC_MonitoringOnly.h"
#include "module_GNC_SwitchOff.h"
#include "module_GNC_AbsLocalisation.h"

#include "module_MAST_DEP_MoveTo.h"
#include "module_MAST_DEP_SwitchOff.h"
#include "module_MAST_PAN_Initialise.h"
#include "module_MAST_PAN_MoveTo.h"
#include "module_MAST_PAN_SwitchOff.h"
#include "module_MAST_PTU_MoveTo.h"
#include "module_MAST_TILT_Initialise.h"
#include "module_MAST_TILT_MoveTo.h"
#include "module_MAST_TILT_SwitchOff.h"
#include "module_SA_LEFT_Primary_Initialise.h"
#include "module_SA_LEFT_Primary_MoveTo.h"
#include "module_SA_LEFT_Primary_SwitchOff.h"
#include "module_SA_LEFT_Secondary_Initialise.h"
#include "module_SA_LEFT_Secondary_MoveTo.h"
#include "module_SA_LEFT_Secondary_SwitchOff.h"
#include "module_SA_RIGHT_Primary_Initialise.h"
#include "module_SA_RIGHT_Primary_MoveTo.h"
#include "module_SA_RIGHT_Primary_SwitchOff.h"
#include "module_SA_RIGHT_Secondary_Initialise.h"
#include "module_SA_RIGHT_Secondary_MoveTo.h"
#include "module_SA_RIGHT_Secondary_SwitchOff.h"

#include "module_PanCam_Initialise.h"
#include "module_PanCam_PIUSwitchOff.h"

#include "module_RV_PostComms.h"
#include "module_RV_Prepare4Comms.h"
#include "module_RV_Prepare4Dozing.h"
#include "module_RV_Prepare4Night.h"
#include "module_RV_Prepare4Science.h"
#include "module_RV_Prepare4Travel.h"
#include "module_RV_SwitchOffMobility.h"
#include "module_RV_WakeUp.h"
#include "module_Release_Body.h"
#include "module_Release_Umbilical.h"

#include "module_MMS_WaitRelTime.h"
#include "module_MMS_WaitAbsTime.h"

